import {
  TbArrowDownRightCircle,
  TbBike,
  TbBrandGithub,
  TbBrandVue,
  TbCapture,
  TbCup,
  TbDental,
  TbCrane,
  TbButterfly,
  TbBrandAndroid,
  TbCell,
  TbLemon2,
  TbMoodCrazyHappy,
  TbRadioactive,
  TbLemon,
} from 'react-icons/tb'
export const categories = [
  { name: '요리용디 Yori Yongd', icon: <TbArrowDownRightCircle /> },
  { name: '스완SWAN_비욘드그루밍 ', icon: <TbBike /> },
  { name: '워크맨-Workman', icon: <TbBrandGithub /> },
  { name: '주둥이방송', icon: <TbBrandVue /> },
  { name: '옛능 : MBC 옛날 예능 다시보기', icon: <TbCapture /> },
  { name: '웅이woongei', icon: <TbLemon /> },
  { name: '혜안', icon: <TbCup /> },
  { name: '미선임파서블 MISUN:IMPOSSIBLE', icon: <TbDental /> },
  { name: '총몇명', icon: <TbCrane /> },
  { name: '공부왕찐천재 홍진경', icon: <TbButterfly /> },
  { name: '끼룩푸드 seagull food', icon: <TbBrandAndroid /> },
  { name: '너덜트', icon: <TbLemon2 /> },
  { name: '언더커버', icon: <TbCell /> },
  { name: '숏박스', icon: <TbRadioactive /> },
  { name: '장삐쭈 ', icon: <TbMoodCrazyHappy /> },
]
